const fs = require('fs');
const path = require('path');

const files = [
  { path: 'src/components/layout/Header.tsx', content: "import React from 'react';\nexport const Header: React.FC = () => <div>Header Placeholder</div>;\nexport default Header;" },
  { path: 'src/components/layout/Sidebar.tsx', content: "import React from 'react';\nexport const Sidebar: React.FC = () => <div>Sidebar Placeholder</div>;\nexport default Sidebar;" },
  { path: 'src/components/layout/BottomNavigation.tsx', content: "import React from 'react';\nexport const BottomNavigation: React.FC = () => <div>BottomNavigation Placeholder</div>;\nexport default BottomNavigation;" },
  { path: 'src/components/layout/TopNavigation.tsx', content: "import React from 'react';\nexport const TopNavigation: React.FC = () => <div>TopNavigation Placeholder</div>;\nexport default TopNavigation;" },
  { path: 'src/components/layout/DrawerMenu.tsx', content: "import React from 'react';\nexport const DrawerMenu: React.FC = () => <div>DrawerMenu Placeholder</div>;\nexport default DrawerMenu;" },
  { path: 'src/components/layout/SearchBar.tsx', content: "import React from 'react';\nexport const SearchBar: React.FC = () => <div>SearchBar Placeholder</div>;\nexport default SearchBar;" },
  { path: 'src/components/layout/AppToolbar.tsx', content: "import React from 'react';\nexport const AppToolbar: React.FC = () => <div>AppToolbar Placeholder</div>;\nexport default AppToolbar;" },
  { path: 'src/components/layout/Breadcrumbs.tsx', content: "import React from 'react';\nexport const Breadcrumbs: React.FC = () => <div>Breadcrumbs Placeholder</div>;\nexport default Breadcrumbs;" },
  { path: 'src/components/layout/FloatingActionButton.tsx', content: "import React from 'react';\nexport const FloatingActionButton: React.FC = () => <div>FloatingActionButton Placeholder</div>;\nexport default FloatingActionButton;" },
  { path: 'src/components/layout/LayoutContainer.tsx', content: "import React from 'react';\nexport const LayoutContainer: React.FC = () => <div>LayoutContainer Placeholder</div>;\nexport default LayoutContainer;" },

  { path: 'src/components/files/FileCard.tsx', content: "import React from 'react';\nexport const FileCard: React.FC = () => <div>FileCard Placeholder</div>;\nexport default FileCard;" },
  { path: 'src/components/files/FileList.tsx', content: "import React from 'react';\nexport const FileList: React.FC = () => <div>FileList Placeholder</div>;\nexport default FileList;" },
  { path: 'src/components/files/FileGrid.tsx', content: "import React from 'react';\nexport const FileGrid: React.FC = () => <div>FileGrid Placeholder</div>;\nexport default FileGrid;" },
  { path: 'src/components/files/FileIcon.tsx', content: "import React from 'react';\nexport const FileIcon: React.FC = () => <div>FileIcon Placeholder</div>;\nexport default FileIcon;" },
  { path: 'src/components/files/FilePreview.tsx', content: "import React from 'react';\nexport const FilePreview: React.FC = () => <div>FilePreview Placeholder</div>;\nexport default FilePreview;" },
  { path: 'src/components/files/FileMenu.tsx', content: "import React from 'react';\nexport const FileMenu: React.FC = () => <div>FileMenu Placeholder</div>;\nexport default FileMenu;" },
  { path: 'src/components/files/FileDetails.tsx', content: "import React from 'react';\nexport const FileDetails: React.FC = () => <div>FileDetails Placeholder</div>;\nexport default FileDetails;" },
  { path: 'src/components/files/FileProperties.tsx', content: "import React from 'react';\nexport const FileProperties: React.FC = () => <div>FileProperties Placeholder</div>;\nexport default FileProperties;" },
  { path: 'src/components/files/FileSelectionBar.tsx', content: "import React from 'react';\nexport const FileSelectionBar: React.FC = () => <div>FileSelectionBar Placeholder</div>;\nexport default FileSelectionBar;" },
  { path: 'src/components/files/FilePathBar.tsx', content: "import React from 'react';\nexport const FilePathBar: React.FC = () => <div>FilePathBar Placeholder</div>;\nexport default FilePathBar;" },
  { path: 'src/components/files/FileThumbnail.tsx', content: "import React from 'react';\nexport const FileThumbnail: React.FC = () => <div>FileThumbnail Placeholder</div>;\nexport default FileThumbnail;" },
  { path: 'src/components/files/FileActions.tsx', content: "import React from 'react';\nexport const FileActions: React.FC = () => <div>FileActions Placeholder</div>;\nexport default FileActions;" },
  { path: 'src/components/files/FileSortMenu.tsx', content: "import React from 'react';\nexport const FileSortMenu: React.FC = () => <div>FileSortMenu Placeholder</div>;\nexport default FileSortMenu;" },
  { path: 'src/components/files/FileFilterMenu.tsx', content: "import React from 'react';\nexport const FileFilterMenu: React.FC = () => <div>FileFilterMenu Placeholder</div>;\nexport default FileFilterMenu;" },
  { path: 'src/components/files/FileRenameDialog.tsx', content: "import React from 'react';\nexport const FileRenameDialog: React.FC = () => <div>FileRenameDialog Placeholder</div>;\nexport default FileRenameDialog;" },
  { path: 'src/components/files/FileDeleteDialog.tsx', content: "import React from 'react';\nexport const FileDeleteDialog: React.FC = () => <div>FileDeleteDialog Placeholder</div>;\nexport default FileDeleteDialog;" },
  { path: 'src/components/files/FileCopyDialog.tsx', content: "import React from 'react';\nexport const FileCopyDialog: React.FC = () => <div>FileCopyDialog Placeholder</div>;\nexport default FileCopyDialog;" },
  { path: 'src/components/files/FileMoveDialog.tsx', content: "import React from 'react';\nexport const FileMoveDialog: React.FC = () => <div>FileMoveDialog Placeholder</div>;\nexport default FileMoveDialog;" },
  { path: 'src/components/files/FavoriteFileCard.tsx', content: "import React from 'react';\nexport const FavoriteFileCard: React.FC = () => <div>FavoriteFileCard Placeholder</div>;\nexport default FavoriteFileCard;" },
  { path: 'src/components/files/RecentFileCard.tsx', content: "import React from 'react';\nexport const RecentFileCard: React.FC = () => <div>RecentFileCard Placeholder</div>;\nexport default RecentFileCard;" },

  { path: 'src/components/viewer/ViewerToolbar.tsx', content: "import React from 'react';\nexport const ViewerToolbar: React.FC = () => <div>ViewerToolbar Placeholder</div>;\nexport default ViewerToolbar;" },
  { path: 'src/components/viewer/ViewerLoader.tsx', content: "import React from 'react';\nexport const ViewerLoader: React.FC = () => <div>ViewerLoader Placeholder</div>;\nexport default ViewerLoader;" },
  { path: 'src/components/viewer/ViewerHeader.tsx', content: "import React from 'react';\nexport const ViewerHeader: React.FC = () => <div>ViewerHeader Placeholder</div>;\nexport default ViewerHeader;" },
  { path: 'src/components/viewer/ViewerFooter.tsx', content: "import React from 'react';\nexport const ViewerFooter: React.FC = () => <div>ViewerFooter Placeholder</div>;\nexport default ViewerFooter;" },
  { path: 'src/components/viewer/PageNavigator.tsx', content: "import React from 'react';\nexport const PageNavigator: React.FC = () => <div>PageNavigator Placeholder</div>;\nexport default PageNavigator;" },
  { path: 'src/components/viewer/ThumbnailSidebar.tsx', content: "import React from 'react';\nexport const ThumbnailSidebar: React.FC = () => <div>ThumbnailSidebar Placeholder</div>;\nexport default ThumbnailSidebar;" },
  { path: 'src/components/viewer/ZoomControls.tsx', content: "import React from 'react';\nexport const ZoomControls: React.FC = () => <div>ZoomControls Placeholder</div>;\nexport default ZoomControls;" },
  { path: 'src/components/viewer/RotateControls.tsx', content: "import React from 'react';\nexport const RotateControls: React.FC = () => <div>RotateControls Placeholder</div>;\nexport default RotateControls;" },
  { path: 'src/components/viewer/SearchInDocument.tsx', content: "import React from 'react';\nexport const SearchInDocument: React.FC = () => <div>SearchInDocument Placeholder</div>;\nexport default SearchInDocument;" },
  { path: 'src/components/viewer/ViewerSettings.tsx', content: "import React from 'react';\nexport const ViewerSettings: React.FC = () => <div>ViewerSettings Placeholder</div>;\nexport default ViewerSettings;" },
  { path: 'src/components/viewer/PdfPageNumber.tsx', content: "import React from 'react';\nexport const PdfPageNumber: React.FC = () => <div>PdfPageNumber Placeholder</div>;\nexport default PdfPageNumber;" },
  { path: 'src/components/viewer/PdfThumbnailList.tsx', content: "import React from 'react';\nexport const PdfThumbnailList: React.FC = () => <div>PdfThumbnailList Placeholder</div>;\nexport default PdfThumbnailList;" },
  { path: 'src/components/viewer/PptSlideNavigator.tsx', content: "import React from 'react';\nexport const PptSlideNavigator: React.FC = () => <div>PptSlideNavigator Placeholder</div>;\nexport default PptSlideNavigator;" },
  { path: 'src/components/viewer/SpreadsheetTabs.tsx', content: "import React from 'react';\nexport const SpreadsheetTabs: React.FC = () => <div>SpreadsheetTabs Placeholder</div>;\nexport default SpreadsheetTabs;" },
  { path: 'src/components/viewer/SpreadsheetToolbar.tsx', content: "import React from 'react';\nexport const SpreadsheetToolbar: React.FC = () => <div>SpreadsheetToolbar Placeholder</div>;\nexport default SpreadsheetToolbar;" },
  { path: 'src/components/viewer/MediaControls.tsx', content: "import React from 'react';\nexport const MediaControls: React.FC = () => <div>MediaControls Placeholder</div>;\nexport default MediaControls;" },
  { path: 'src/components/viewer/AudioControls.tsx', content: "import React from 'react';\nexport const AudioControls: React.FC = () => <div>AudioControls Placeholder</div>;\nexport default AudioControls;" },
  { path: 'src/components/viewer/VideoControls.tsx', content: "import React from 'react';\nexport const VideoControls: React.FC = () => <div>VideoControls Placeholder</div>;\nexport default VideoControls;" },

  { path: 'src/components/tools/ToolCard.tsx', content: "import React from 'react';\nexport const ToolCard: React.FC = () => <div>ToolCard Placeholder</div>;\nexport default ToolCard;" },
  { path: 'src/components/tools/ToolGrid.tsx', content: "import React from 'react';\nexport const ToolGrid: React.FC = () => <div>ToolGrid Placeholder</div>;\nexport default ToolGrid;" },
  { path: 'src/components/tools/ToolCategory.tsx', content: "import React from 'react';\nexport const ToolCategory: React.FC = () => <div>ToolCategory Placeholder</div>;\nexport default ToolCategory;" },
  { path: 'src/components/tools/ToolHeader.tsx', content: "import React from 'react';\nexport const ToolHeader: React.FC = () => <div>ToolHeader Placeholder</div>;\nexport default ToolHeader;" },
  { path: 'src/components/tools/ToolProgress.tsx', content: "import React from 'react';\nexport const ToolProgress: React.FC = () => <div>ToolProgress Placeholder</div>;\nexport default ToolProgress;" },
  { path: 'src/components/tools/ToolResult.tsx', content: "import React from 'react';\nexport const ToolResult: React.FC = () => <div>ToolResult Placeholder</div>;\nexport default ToolResult;" },
  { path: 'src/components/tools/ToolSuccess.tsx', content: "import React from 'react';\nexport const ToolSuccess: React.FC = () => <div>ToolSuccess Placeholder</div>;\nexport default ToolSuccess;" },
  { path: 'src/components/tools/ToolError.tsx', content: "import React from 'react';\nexport const ToolError: React.FC = () => <div>ToolError Placeholder</div>;\nexport default ToolError;" },
  { path: 'src/components/tools/PdfToolCard.tsx', content: "import React from 'react';\nexport const PdfToolCard: React.FC = () => <div>PdfToolCard Placeholder</div>;\nexport default PdfToolCard;" },
  { path: 'src/components/tools/ImageToolCard.tsx', content: "import React from 'react';\nexport const ImageToolCard: React.FC = () => <div>ImageToolCard Placeholder</div>;\nexport default ImageToolCard;" },
  { path: 'src/components/tools/OfficeToolCard.tsx', content: "import React from 'react';\nexport const OfficeToolCard: React.FC = () => <div>OfficeToolCard Placeholder</div>;\nexport default OfficeToolCard;" },
  { path: 'src/components/tools/ArchiveToolCard.tsx', content: "import React from 'react';\nexport const ArchiveToolCard: React.FC = () => <div>ArchiveToolCard Placeholder</div>;\nexport default ArchiveToolCard;" },
  { path: 'src/components/tools/ProcessingAnimation.tsx', content: "import React from 'react';\nexport const ProcessingAnimation: React.FC = () => <div>ProcessingAnimation Placeholder</div>;\nexport default ProcessingAnimation;" },
  { path: 'src/components/tools/DownloadResult.tsx', content: "import React from 'react';\nexport const DownloadResult: React.FC = () => <div>DownloadResult Placeholder</div>;\nexport default DownloadResult;" },
  { path: 'src/components/tools/ShareResult.tsx', content: "import React from 'react';\nexport const ShareResult: React.FC = () => <div>ShareResult Placeholder</div>;\nexport default ShareResult;" },
  { path: 'src/components/tools/FilePicker.tsx', content: "import React from 'react';\nexport const FilePicker: React.FC = () => <div>FilePicker Placeholder</div>;\nexport default FilePicker;" },
  { path: 'src/components/tools/ConversionProgress.tsx', content: "import React from 'react';\nexport const ConversionProgress: React.FC = () => <div>ConversionProgress Placeholder</div>;\nexport default ConversionProgress;" },

  { path: 'src/components/ads/BannerAd.tsx', content: "import React from 'react';\nexport const BannerAd: React.FC = () => <div>BannerAd Placeholder</div>;\nexport default BannerAd;" },
  { path: 'src/components/ads/NativeAd.tsx', content: "import React from 'react';\nexport const NativeAd: React.FC = () => <div>NativeAd Placeholder</div>;\nexport default NativeAd;" },
  { path: 'src/components/ads/InterstitialAd.tsx', content: "import React from 'react';\nexport const InterstitialAd: React.FC = () => <div>InterstitialAd Placeholder</div>;\nexport default InterstitialAd;" },
  { path: 'src/components/ads/RewardedAd.tsx', content: "import React from 'react';\nexport const RewardedAd: React.FC = () => <div>RewardedAd Placeholder</div>;\nexport default RewardedAd;" },
  { path: 'src/components/ads/AppOpenAd.tsx', content: "import React from 'react';\nexport const AppOpenAd: React.FC = () => <div>AppOpenAd Placeholder</div>;\nexport default AppOpenAd;" },
  { path: 'src/components/ads/AdPlaceholder.tsx', content: "import React from 'react';\nexport const AdPlaceholder: React.FC = () => <div>AdPlaceholder Placeholder</div>;\nexport default AdPlaceholder;" },
  { path: 'src/components/ads/AdContainer.tsx', content: "import React from 'react';\nexport const AdContainer: React.FC = () => <div>AdContainer Placeholder</div>;\nexport default AdContainer;" },
  { path: 'src/components/ads/AdError.tsx', content: "import React from 'react';\nexport const AdError: React.FC = () => <div>AdError Placeholder</div>;\nexport default AdError;" },

  { path: 'src/components/common/LoadingScreen.tsx', content: "import React from 'react';\nexport const LoadingScreen: React.FC = () => <div>LoadingScreen Placeholder</div>;\nexport default LoadingScreen;" },
  { path: 'src/components/common/SplashScreen.tsx', content: "import React from 'react';\nexport const SplashScreen: React.FC = () => <div>SplashScreen Placeholder</div>;\nexport default SplashScreen;" },
  { path: 'src/components/common/EmptyState.tsx', content: "import React from 'react';\nexport const EmptyState: React.FC = () => <div>EmptyState Placeholder</div>;\nexport default EmptyState;" },
  { path: 'src/components/common/ErrorState.tsx', content: "import React from 'react';\nexport const ErrorState: React.FC = () => <div>ErrorState Placeholder</div>;\nexport default ErrorState;" },
  { path: 'src/components/common/SuccessState.tsx', content: "import React from 'react';\nexport const SuccessState: React.FC = () => <div>SuccessState Placeholder</div>;\nexport default SuccessState;" },
  { path: 'src/components/common/ConfirmDialog.tsx', content: "import React from 'react';\nexport const ConfirmDialog: React.FC = () => <div>ConfirmDialog Placeholder</div>;\nexport default ConfirmDialog;" },
  { path: 'src/components/common/AlertDialog.tsx', content: "import React from 'react';\nexport const AlertDialog: React.FC = () => <div>AlertDialog Placeholder</div>;\nexport default AlertDialog;" },
  { path: 'src/components/common/ProgressDialog.tsx', content: "import React from 'react';\nexport const ProgressDialog: React.FC = () => <div>ProgressDialog Placeholder</div>;\nexport default ProgressDialog;" },
  { path: 'src/components/common/PermissionCard.tsx', content: "import React from 'react';\nexport const PermissionCard: React.FC = () => <div>PermissionCard Placeholder</div>;\nexport default PermissionCard;" },
  { path: 'src/components/common/PermissionDialog.tsx', content: "import React from 'react';\nexport const PermissionDialog: React.FC = () => <div>PermissionDialog Placeholder</div>;\nexport default PermissionDialog;" },
  { path: 'src/components/common/NotificationCard.tsx', content: "import React from 'react';\nexport const NotificationCard: React.FC = () => <div>NotificationCard Placeholder</div>;\nexport default NotificationCard;" },
  { path: 'src/components/common/SettingsCard.tsx', content: "import React from 'react';\nexport const SettingsCard: React.FC = () => <div>SettingsCard Placeholder</div>;\nexport default SettingsCard;" },
  { path: 'src/components/common/SearchInput.tsx', content: "import React from 'react';\nexport const SearchInput: React.FC = () => <div>SearchInput Placeholder</div>;\nexport default SearchInput;" },
  { path: 'src/components/common/CategoryChip.tsx', content: "import React from 'react';\nexport const CategoryChip: React.FC = () => <div>CategoryChip Placeholder</div>;\nexport default CategoryChip;" },
  { path: 'src/components/common/SortMenu.tsx', content: "import React from 'react';\nexport const SortMenu: React.FC = () => <div>SortMenu Placeholder</div>;\nexport default SortMenu;" },
  { path: 'src/components/common/FilterMenu.tsx', content: "import React from 'react';\nexport const FilterMenu: React.FC = () => <div>FilterMenu Placeholder</div>;\nexport default FilterMenu;" },
  { path: 'src/components/common/ThemeSwitcher.tsx', content: "import React from 'react';\nexport const ThemeSwitcher: React.FC = () => <div>ThemeSwitcher Placeholder</div>;\nexport default ThemeSwitcher;" },
  { path: 'src/components/common/LanguageSelector.tsx', content: "import React from 'react';\nexport const LanguageSelector: React.FC = () => <div>LanguageSelector Placeholder</div>;\nexport default LanguageSelector;" },
  { path: 'src/components/common/StorageIndicator.tsx', content: "import React from 'react';\nexport const StorageIndicator: React.FC = () => <div>StorageIndicator Placeholder</div>;\nexport default StorageIndicator;" },
  { path: 'src/components/common/MemoryIndicator.tsx', content: "import React from 'react';\nexport const MemoryIndicator: React.FC = () => <div>MemoryIndicator Placeholder</div>;\nexport default MemoryIndicator;" },
  { path: 'src/components/common/StatusBadge.tsx', content: "import React from 'react';\nexport const StatusBadge: React.FC = () => <div>StatusBadge Placeholder</div>;\nexport default StatusBadge;" },
  { path: 'src/components/common/EmptyFolder.tsx', content: "import React from 'react';\nexport const EmptyFolder: React.FC = () => <div>EmptyFolder Placeholder</div>;\nexport default EmptyFolder;" },
  { path: 'src/components/common/NoResults.tsx', content: "import React from 'react';\nexport const NoResults: React.FC = () => <div>NoResults Placeholder</div>;\nexport default NoResults;" },
  { path: 'src/components/common/OfflineIndicator.tsx', content: "import React from 'react';\nexport const OfflineIndicator: React.FC = () => <div>OfflineIndicator Placeholder</div>;\nexport default OfflineIndicator;" },

  { path: 'src/hooks/useFiles.ts', content: "export const useFiles = () => {};\nexport default useFiles;" },
  { path: 'src/hooks/useViewer.ts', content: "export const useViewer = () => {};\nexport default useViewer;" },
  { path: 'src/hooks/useSearch.ts', content: "export const useSearch = () => {};\nexport default useSearch;" },
  { path: 'src/hooks/useStorage.ts', content: "export const useStorage = () => {};\nexport default useStorage;" },
  { path: 'src/hooks/useDownloads.ts', content: "export const useDownloads = () => {};\nexport default useDownloads;" },
  { path: 'src/hooks/usePermissions.ts', content: "export const usePermissions = () => {};\nexport default usePermissions;" },
  { path: 'src/hooks/useNotifications.ts', content: "export const useNotifications = () => {};\nexport default useNotifications;" },
  { path: 'src/hooks/useAds.ts', content: "export const useAds = () => {};\nexport default useAds;" },
  { path: 'src/hooks/useTheme.ts', content: "export const useTheme = () => {};\nexport default useTheme;" },

  { path: 'src/stores/fileStore.ts', content: "export const fileStore = {};\nexport default fileStore;" },
  { path: 'src/stores/viewerStore.ts', content: "export const viewerStore = {};\nexport default viewerStore;" },
  { path: 'src/stores/searchStore.ts', content: "export const searchStore = {};\nexport default searchStore;" },
  { path: 'src/stores/notificationStore.ts', content: "export const notificationStore = {};\nexport default notificationStore;" },
  { path: 'src/stores/settingsStore.ts', content: "export const settingsStore = {};\nexport default settingsStore;" },
  { path: 'src/stores/adStore.ts', content: "export const adStore = {};\nexport default adStore;" },
  { path: 'src/stores/toolStore.ts', content: "export const toolStore = {};\nexport default toolStore;" },

  { path: 'src/utils/fileUtils.ts', content: "export const fileUtils = {};\nexport default fileUtils;" },
  { path: 'src/utils/imageUtils.ts', content: "export const imageUtils = {};\nexport default imageUtils;" },
  { path: 'src/utils/pdfUtils.ts', content: "export const pdfUtils = {};\nexport default pdfUtils;" },
  { path: 'src/utils/zipUtils.ts', content: "export const zipUtils = {};\nexport default zipUtils;" },
  { path: 'src/utils/storageUtils.ts', content: "export const storageUtils = {};\nexport default storageUtils;" },
  { path: 'src/utils/permissionUtils.ts', content: "export const permissionUtils = {};\nexport default permissionUtils;" },
  { path: 'src/utils/shareUtils.ts', content: "export const shareUtils = {};\nexport default shareUtils;" },
  { path: 'src/utils/viewerUtils.ts', content: "export const viewerUtils = {};\nexport default viewerUtils;" },
  { path: 'src/utils/formatUtils.ts', content: "export const formatUtils = {};\nexport default formatUtils;" },
  { path: 'src/utils/dateUtils.ts', content: "export const dateUtils = {};\nexport default dateUtils;" },

  { path: 'src/types/file.ts', content: "export type FileData = any;" },
  { path: 'src/types/fileDetails.ts', content: "export type FileDetails = any;" },
  { path: 'src/types/viewer.ts', content: "export type ViewerState = any;" },
  { path: 'src/types/tool.ts', content: "export type ToolData = any;" },
  { path: 'src/types/sort.ts', content: "export type SortOptions = any;" },
  { path: 'src/types/filter.ts', content: "export type FilterOptions = any;" },
  { path: 'src/types/permissions.ts', content: "export type PermissionsData = any;" },
  { path: 'src/types/notification.ts', content: "export type NotificationData = any;" },
  { path: 'src/types/ads.ts', content: "export type AdData = any;" },
  { path: 'src/types/settings.ts', content: "export type SettingsData = any;" },
  { path: 'src/types/navigation.ts', content: "export type NavigationData = any;" },

  { path: 'src/constants/fileTypes.ts', content: "export const FILE_TYPES = {};" },
  { path: 'src/constants/mimeTypes.ts', content: "export const MIME_TYPES = {};" },
  { path: 'src/constants/sortOptions.ts', content: "export const SORT_OPTIONS = {};" },
  { path: 'src/constants/filterOptions.ts', content: "export const FILTER_OPTIONS = {};" },
  { path: 'src/constants/permissions.ts', content: "export const PERMISSIONS = {};" },
  { path: 'src/constants/adUnits.ts', content: "export const AD_UNITS = {};" },
  { path: 'src/constants/colors.ts', content: "export const COLORS = {};" },
  { path: 'src/constants/appConfig.ts', content: "export const APP_CONFIG = {};" },

  { path: 'src/themes/light.ts', content: "export const lightTheme = {};\nexport default lightTheme;" },
  { path: 'src/themes/dark.ts', content: "export const darkTheme = {};\nexport default darkTheme;" },
  { path: 'src/themes/material3.ts', content: "export const material3Theme = {};\nexport default material3Theme;" },

  { path: 'src/localization/en.ts', content: "export const en = {};\nexport default en;" },
  { path: 'src/localization/hi.ts', content: "export const hi = {};\nexport default hi;" },
  { path: 'src/localization/te.ts', content: "export const te = {};\nexport default te;" },
  { path: 'src/localization/index.ts', content: "export const localization = {};\nexport default localization;" }
];

files.forEach(f => {
  const dir = path.dirname(f.path);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(f.path, f.content);
});

console.log('All files created successfully.');
